name: Terraform Workflow

on: [push]

env:
  TF_LOG: WARN
  WORKSPACE: development
  PATH: ${{ github.workspace }}/bin:$PATH

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Install tar
      run: sudo apt-get install -y tar

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.x

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Change to working directory
      run: |
        cd jenkins-terraform-pipeline/ec2_pipeline/

    - name: Terraform Init
      run: |
        terraform init -input=false

    - name: Terraform Format
      run: |
        terraform fmt -list=true -write=false -diff=true -check=true

    - name: Terraform Validate
      run: |
        terraform validate

    - name: Terraform Plan
      run: |
        terraform workspace new $WORKSPACE || terraform workspace select $WORKSPACE
        terraform plan -var 'access_key=${{ secrets.AWS_ACCESS_KEY_ID }}' -var 'secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -out terraform.tfplan

    - name: Terraform Apply
      run: |
        terraform apply terraform.tfplan
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' 

